project:
  name: DemoProject  # Short project name. Example: PDAC_sn
  work_dir: /work/DemoProject  # Output folder. Example: /work/PDAC_sn

inputs:
  seurat_rds: /data/my_project/my_dataset.rds  # Seurat .rds file. Example: /data/pdac/pdac_sn.rds

annotation:
  species: human  # human or mouse.
  tissue_name: replace_with_your_dataset_tissue  # Dataset context. Example: human pancreatic tumor
  parent_res:  # Parent clustering resolutions to test. Examples: 0.1, 0.3, 0.5
    - 0.1
    - 0.3
